name: Push Chart

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Push Helm chart to OCI compatible registry (Github)
        uses: bsord/helm-push@v4.1.0
        with:
          useOCIRegistry: true
          registry-url: oci://ghcr.io/${{ github.repository }}
          username: ${{ github.actor }}
          access-token: ${{ secrets.GHOCI }}
          force: true
          chart-folder: ./
